title:              52Dreams
email:              spirit.nj@gmail.com
description:        Dream, my life yearning
author:             Andy Hunter
baseurl:            "/clean.github.io"
url:                "https://spiritgs.github.io/clean.github.io"

# Social Profiles
twitter_username:   52dreams_
github_username:    spiritgs
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-KE374S146 # UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
